GENERAL:
  VERSION: '1.0'
CREDENTIALS:
  TOKEN_FILE: './token.txt' # file with BB API token. If you change it, remember to add this file to .gitignore
SETTINGS:
  MODEL_PATH: './models/'
  DATA_PATH: './data/'
  LINETERMINATOR: '\n'